### ISSUE TITLE
Is it possible to fix the texture glitches on level gates and hidden parts of the level?

### ISSUE THREAD

**Issue by Erwandawa123** [TurtleHouse/PizzaTowerSwitch-FMOD#22]

**Comment by TurtleHouse** [comment]
@Erwandawa123 could you upload a screenshot

**Comment by Erwandawa123** [comment]
![Screenshot_2023-08-21-23-37-28-247_skyline emu](https://github.com/TurtleHouse/PizzaTowerSwitch-FMOD/assets/136333521/40c506dd-4277-4f06-b65e-ff039c80ff40)
![Screenshot_2023-08-21-23-15-24-306_skyline emu](https://github.com/TurtleHouse/PizzaTowerSwitch-FMOD/assets/136333521/25d1f4fd-a8bf-4212-83b2-40acaf2eb3d5)

![Screenshot_2023-08-21-23-05-36-542_skyline emu](https://github.com/TurtleHouse/PizzaTowerSwitch-FMOD/assets/136333521/51eaf16b-04db-4fdd-801d-bb0a1eec1cb3)
Hes
![Uploading Screenshot_2023-08-21-23-03-35-828_skyline.emu.jpg…]
![Screenshot_2023-08-21-22-38-21-248_skyline emu](https://github.com/TurtleHouse/PizzaTowerSwitch-FMOD/assets/136333521/a5feb8ee-29ac-4b37-b639-ce327033fb9d)
These are some examples

**Comment by TurtleHouse** [comment]
The issue you are experiencing (and very likely all the previous issues) are caused due to playing the game on an emulator. Please verify that the issues happen on a real console before opening an issue on this repository. It is impossible for the developer to fix emulator exclusive bugs, and it is the emulator's responsibility to be accurate. If you can, you should notify the developers of the emulators if they have a repository or issue tracker.
![spin](https://github.com/TurtleHouse/PizzaTowerSwitch-FMOD/assets/87158297/3936327d-8134-49b6-8382-beb9058890f7)
