### ISSUE TITLE
How about inserting CYOP modifications into the port and russian language? 

### ISSUE THREAD

**Issue by Proshit** [TurtleHouse/PizzaTowerSwitch-FMOD#26]
As for CYOP, it will be easy, since the game already knows how to connect to WiFi, there will only be a few hundred strokes left. And here is the russifier... I'd rather give you a link to GameBanana - https://gamebanana.com/mods/452787.

**Comment by TurtleHouse** [comment]
From the developer:
Just because the port can read a version string from the internet to check for updates doesn't mean anything. Downloading levels from a website is a much more complicated process (I assume that's what you're referring to with the WiFi), and additionally porting the necessary code from CYOP is a challenge itself: Since the port's data.win is different from the vanilla game's data.win, the mod has to be (mostly) manually reconstructed inside the Switch port project, as was done for Lap 3. For this same reason, the Russifier is hard to add as well, and it will not be done by me

**Comment by Proshit** [comment]
Sadly... By the way, will there be the addition of the same 4 lap or what about other mods? If so, which ones?
